Grarak/KernelAdiutor

- app/src/main/res/layout/header_main.xml
When enabled, the "apply on boot" SwitchCompat is ever so slightly chipped off at the right edge. Add a small padding at the end to prevent this, and another padding at the start to balance it out.
> Don't chip off the right edge of SwitchCompat

- app/src/main/res/color/button_text_color.xml
- app/src/main/res/layout/list_item.xml
Hello, I really like your app, and that it is opensource!
I think that the activated fragment on the navigation drawer looks better this way:
I don't really like the black on blue match. I hope you like it, too. :)
> Activated list item: change activated text color

- app/src/main/java/com/grarak/kerneladiutor/MainActivity.java
AlertDialogs are tied to the current window, in this case MainActivity.
Once MainActivity is closed upon calling finish(), the AlertDialog is
not dismissed yet and thus causes a memory leak.
Fix this by dismissing the AlertDialog before closing MainActivity.
> Fix window leak upon exiting MainActivity

- app/src/main/java/com/grarak/kerneladiutor/elements/SwitchCompatCardItem.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUVoltageFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/CPUVoltage.java
- app/src/main/res/values/strings.xml
Adds support for a simple 0/1 attribute at /sys/devices/system/cpu/cpu0/cpufreq/override_vmin.  When enabled on kernels that support it, this attribute forces CPU voltage to remain above a safe limit.
I stuffed some code into SwitchCompatCardItem so that the card would display nicely with the narrow columns in the CPU Voltage fragment.  I'm sure there are better ways to do this, but I'm not sure what they are.
> Add support for override_vmin

- app/src/main/assets/downloads.json
- download/nexus5.json
Nexus 5 compatibility and support for Electroactive Kernel OTA
> Initial support for Nexus 5 (hammerhead) and Electroactive Kernel

- app/src/main/java/com/grarak/kerneladiutor/fragments/tools/RecoveryFragment.java
- app/src/main/res/menu/recovery_menu.xml
- app/src/main/res/values/strings.xml
Option for soft reboot/hot reboot by killing zygote. All the services and apps registered to zygote gets killed and restarted. This effectively decreases reboot time when someone just wants to restart all the apps. The effect is mostly noticeable on older devices.
Busybox is required for pkill/killall commands.
> Recovery: Add option for Soft Reboot

- app/src/main/assets/downloads.json
Vendor was written as "Cherry" but it's "Cherry Mobile" Maybe this is causing users not getting download section on the latest version too.
> It's "Cherry Mobile"

- app/src/main/assets/downloads.json
- download/xperiasp.json
Good morrow,
I added all the needed files to enable download support for my kernel. I tested the new download.json file and it works.
Thanks for your attention,
Tommaso Fonda
Tomoms @ xda-developers
> Add download support for Tangerine kernel for Xperia SP

- app/src/main/java/com/grarak/kerneladiutor/fragments/other/SettingsFragment.java
In newer 3.10 kernels, the ramoops drivers saves the kernel panic messages.
> Settings: Add support for pstore last kmsg

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Misc.java
A kernel patch by franciscofranco also enables the ability to
disable/enable fsync in the exact same fashion as the previous parameter
(which devices even have this parameter?) and has been implemented in
various kernels. This does not break the old parameter or anything new.
This also closes #195.
[v2]: Simplify code and squash. 1 = y.
> kernel: Add support for a different fsync path

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUHotplugFragment.java
- app/src/main/res/values/strings.xml
strings: Fix idle_wait_summary string:
Correct to \'s to properly append an apostrophe. Currently shows as "The idlewait\'th events..." in the app and the intended string should be "The idlewait's events".
MSM_Hotplug: Use debug string over debug mask string:
The default debug mask string references CPU boost, which is a separate module from MSM_Hotplug. The easiest solution to this is to use the generic debug string (Which makes it consistent with intelli hotplug as well).
> strings: Consistency update

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/SoundFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Sound.java
- app/src/main/res/values/strings.xml
* Some custom kernels for Qualcomm devices offer a "headset high performance mode" option, which makes audio be output at 24 bit @ 192kHz at all times. We're adding a toggle for that.
* Plus, we're fixing a few grammar errors in the misc section.
> Add support for Headset High Performance Mode

- app/src/main/assets/downloads.json
- download/bullhead.json
This adds download support for ElementalX as the first kernel for the Nexus 5X.
> Add download support for the Nexus 5X (bullhead)

- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Misc.java
* This allows for a 599 value difference in the case it's 715
and the maximum difference should always be 300
> vibration: Fix Derp for Nexus 6P

- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/cpu/MSMPerformance.java
this is a renamed cpu_max_freq, in order to prevent stock software from enforcing their own
max frequencies
> MSMPerformance: add support for max_cpu_freq

- app/src/main/assets/temp.json
commit 0b3971045832929e8f57956cdad4fce0b171c5b7 added GPU temp for apq8084.
/sys/class/thermal/thermal_zone11/temp contains the temp in degC * 1000, so fix the
gpu-offset value accordingly.
Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
> apq8084: Fix GPU multiplicator

- download/s2.json
This is because the AndroModX Kernel's main branch was updated and this commit fixes the links and adds the new links to support Kernel Adiutor.
> Update s2.json as the Kernel got updated to support cm13 roms

- app/src/main/assets/temp.json
Comparing results on shamu/quark/kccat6 imply that the GPU's
thermal_zone is actually 10, not 11.  11 appears to be some arbitrary,
device-specific sensor, given the differing readouts on different
devices.  For a discussion see
https://github.com/Grarak/KernelAdiutor/commit/0b397104
Signed-off-by: Corinna Vinschen <corinna@vinschen.de>
> apq8084: Fix thermal_zone for GPU

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/VMFragment.java
1024M is too small for some devices.
> enlarge zram.setMax

- download/x3.json
Sorry, I just Noticed that there was a broken link in my .json file that was creating issue!
Merge this one and the Downloader for x3 will also start working fine!
> Fixed a Messed Link that was creating issues with downloader

- app/src/main/assets/downloads.json
- download/bullhead.json
I don't have time to maintain the downloads anymore.
The repo it pointed to is already removed since it only contained VERY outdated versions.
> Remove download of ElementalX for bullhead

- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/cpu/Temperature.java
Commit https://github.com/Grarak/KernelAdiutor/commit/30ccfff54a7fe4c74a3ba98a54717a41a3bc8e39 were causing a bug in my device (Yureka - msm8939) in which temperature stats  was showing temp in .05 C instead 50 C.
Reverting that changes in temperature.java fixes the issue.
> Fix Temperature Calculation bug.
