Grarak/KernelAdiutor

- app/src/main/res/values-zh-CN/strings.xml
initial version of zh-CN translation, need to be improved later.
> KernelAdiutor: Add Simplified Chinese Translation

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
Hello this is the path to nexus 10 dt2w.
> add manta gesture support

- app/src/main/assets/downloads.json
- download/g3.json
LG G3 support for 777 Kernel OTA
> Add support for LG G3

- download/sprout.json
Adding Zeus kernel to downloads, so that I don't have to share the link again and again.
> Add Zeus Kernel

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/CPU.java
- app/src/main/res/values/strings.xml
enable oc steps when new max cpu frequency is selected.
Also thanks to USA-RedDragon for helping out with this.
Signed-off-by: BlackDragon <blackdragon.fusionteam@gmail.com>
> Add Ktoonsez logic for maximum frequency and UV table. 

- app/src/main/java/com/grarak/kerneladiutor/fragments/tools/ProfileFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/database/ProfileDB.java
- app/src/main/res/values/strings.xml
Previously, it was possible to create profiles with the same names.
I added a check for existence of the profile and confirmation dialog box to overwrite the old profile with same name.
Previous similar profiles are not broken.
> Unique profiles

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
Used in Xperia L, M, Z and other devices
> KernelAdiutor: Add another sysfs node for vibrator

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/CPU.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Wake.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
Signed-off-by: Pafcholini <nadyaivanova14@gmail.com>
> CPU: add wakeup boost and hotplug boost

- app/src/main/assets/downloads.json
- download/quark.json
I have tested on my device this is 100% working.
Off course in my test I replace the path for download/quark to the one in my source, but in this commit it point to yours. The main json is place in my source and is working.
Thanks for the great work.
> Downloads: Add support for quark.

- app/src/main/assets/downloads.json
I found some other device name for quark.
> Downloads: quark included more devices.

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
Change-Id: Iec55ff525ba733f4ebda514dfa4f6b537f653202
> Logger: Add Additional Sysfs

- app/src/main/assets/downloads.json
- download/tomato.json
Signed-off-by: HridayHS <hridaysharma42@gmail.com>
> downloads: add support for Lightning-Kernel

- download/tomato.json
downloads : Add support for Xeon kernel for YU Yureka / Yureka+
> Add Xeon kernel support for YU Yureka

- download/xperiasp.json
Remove support for my old kernel and add support for my new one.
> update Xperia SP download section

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Misc.java
> vibration: Support Nexus 6P

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Wake.java
- app/src/main/res/values/strings.xml
For this commit:
https://github.com/flar2/angler/commit/5d10751af74617c23dfaf93bdf8149e39ce6da41
> Wake: Enable Camera Gesture switch

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/CPUHotplug.java
- app/src/main/res/values/strings.xml
* Relevant Kernel Change is here: https://github.com/CandyDevices/kernel_samsung_jf/commit/7b939e73d0ba8193479f9b38aa109fe6b91ce9af
* javelinanddart: Preform Sysfs Check as to not break everything
> intelli_plug: Add InSaNiTy Profiles

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Wake.java
- app/src/main/res/values/strings.xml
> wake: Add Sweep2Wake Leniency Toggle

- app/src/main/assets/downloads.json
@Grarak, another Yu SmartPhone. :D Just shows my love for your kernel-management app. :)
> Add Support for Yu Yunique

- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Wake.java
- app/src/main/res/values/strings.xml
> wake: Add another Pocket Mode Sysfs

- app/src/main/assets/downloads.json
- download/elixir_r2.json
Added Elixir kernel support for xiaomi devices.
> Added Suport for Xiaomi devices

- download/lettuce.json
- download/lettuce.json~
Signed-off-by: The-Demon12 <kartikbhalla12@gmail.com>
> Added Support for Phenex Kernel

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/SoundFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/sound/Sound.java
- app/src/main/res/values/strings.xml
This should be good. Please merge before i end up screwing everything up again, im a very forgetful person :p
> Fix faux sound & add tpa6165

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/ScreenFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Screen.java
Adds a checkbox for mdss_fb backlight_dimmer parameter in the elementalX kernel for the Nexus 5X (and possibly others too).
> screen: add mdss_fb backlight_dimmer option

- app/src/main/java/com/grarak/kerneladiutor/MainActivity.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/LedFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/SoundFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/VMFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFragment.java
- app/src/main/java/com/grarak/kerneladiutor/services/BootService.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Constants.java
- app/src/main/java/com/grarak/kerneladiutor/utils/Utils.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/CPU.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Led.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Sound.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/VM.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/Wake.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
Note 4 users need hard limit parameters to make OC. Without the hard limit we can't get more than 2.6GHz
Signed-off-by: Pafcholini <nadyaivanova14@gmail.com>
> CPU: add Hard Limit

- app/src/main/assets/downloads.json
- download/galaxys7.json
- download/galaxys7edge.json
Added devices:
heroltexx (Samsung Galaxy S7)
hero2ltexx (Samsung Galaxy S7 Edge)
Files added:
downloads/galaxys7.json
downloads/galaxys7edge.json
Signed-off-by: djb77 <dwayne.bakewell@gmail.com>
> Samsung Galaxy S7 / S7 Edge Support

- app/src/main/assets/downloads.json
- download/nicki.json
Okay, here you are sir. I'm already squash it into 1 commit.
Thanks for your response :+1:
> SQUASH : Xperia M Kernel

- app/src/main/assets/downloads.json
- download/nicki.json
Update "nicki" for AOSP and CM Custom ROM compatibility.
>  Update nicki compatibility

- app/src/main/assets/downloads.json
- download/falcon.json
- download/peregrine.json
Add support for Moto G 2013 and 4G variant too (falcon and peregrine) and add my kernel to the download section.
> Add support for Falcon and Peregrine and add my kernel

- app/src/main/assets/downloads.json
- download/s2.json
@Grarak Sir Please Merge this Pull Request Soon
> Add Support For LeEco Le 2 AndroModX Kernel

- app/src/main/assets/downloads.json
Sir, could you please add new integrated to Xperia M? (Lineage OS)
:D
> Integrated Lineage OS for Xperia M

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/BatteryFragment.java
Signed-off-by: AyushR1 <ayushrathore12501@gmail.com>
> ThunderCharge: Fix Charge current not changing bug.

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/SoundFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/sound/Sound.java
Even though flar2 has allowed the reduction of the headphone's gain to -84, I've set it to be up to -40
https://github.com/Grarak/KernelAdiutor/issues/494
Any code suggestion would be appreciated as I don't pretty much know java
> Add support for flar2's sound control

- app/build.gradle
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFrament.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/wake/Dt2w.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/wake/Misc.java
- app/src/main/res/values/strings.xml
Corresponding kernel changes : 'https://github.com/YUDHPK/android_kernel_samsung_smdk4412/commits/cm-14.1'
Reference for commit : 'https://github.com/makorn645/KernelAdiutor/commits/master'
Author:    makorn645 <makorn645@github.com>
> Adding touch2wake support for SMDK4412 kernel with timeout features

- app/src/main/java/com/grarak/kerneladiutor/activities/NavigationActivity.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/ApplyOnBootFragment.java
- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/WakeFragment.java
> Fix WakeFrament typos

- app/src/main/java/com/grarak/kerneladiutor/fragments/kernel/CPUHotplugFragment.java
- app/src/main/java/com/grarak/kerneladiutor/utils/kernel/cpuhotplug/CoreCtl.java
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Add Online Delay for CPUHotplug
